services:
  employeedb:
    image: mysql
    container_name: employeedb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: employeemanager
      MYSQL_ROOT_PASSWORD: root



