services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8085:80"

  employeedb:
      image: mysql
      container_name: employeedb
      ports:
        - "3307:3306"
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        timeout: 10s
        retries: 10
        interval: 10s
        start_period: 10s
      environment:
        MYSQL_DATABASE: employeemanager
        MYSQL_ROOT_PASSWORD: root

  employee:
      image: "fadhiljr/nginxapp:employee-backend-v13"
      container_name: employee
      ports:
        - "8080:8080"
      depends_on:
        employeedb:
          condition: service_healthy
        nginx:
          condition: service_started
      environment:
        SPRING_APPLICATION_NAME: "employee"
        SPRING_DATASOURCE_URL: "jdbc:mysql://employeedb:3306/employeemanager"
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "root"

  employeev2:
      image: "fadhiljr/nginxapp:employee-backend-v13"
      container_name: employeev2
      ports:
        - "8081:8080"
      depends_on:
        employeedb:
          condition: service_healthy
        nginx:
          condition: service_started
      environment:
        SPRING_APPLICATION_NAME: "employee"
        SPRING_DATASOURCE_URL: "jdbc:mysql://employeedb:3306/employeemanager"
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "root"

  client:
      image: fadhiljr/nginxapp:employee-frontend-v15
      container_name: employeemanagerfrontend
      ports:
        - "443:443"

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana:9.5.2
      container_name: grafana
      ports:
        - "3000:3000"
      restart: unless-stopped
      volumes:
        - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

