server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://database-1.c9iouucc2x0o.us-east-1.rds.amazonaws.com:3306/employeemanager
    password: WN6TE5DpDD0ESDd2OuJq
    username: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"