server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"

management:
  endpoints:
    web:
      exposure:
        include: "*"

