apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
        tier: frontend
    spec:
      containers:
        - name: employee-frontend
          image: fadhiljr/nginxapp:employee-frontend-v12
          ports:
            - containerPort: 80
