apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default # Change as needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-db-password
            - name: MYSQL_DATABASE
              value: employeemanager
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: employee-db-creation
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: ebs-pvc-mysql
        - name: employee-db-creation
          configMap:
            name: employee-db-creation